version: "3.3"
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=dani
      - POSTGRES_PASSWORD=admin1234
    ports:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
